### ISSUE TITLE
Kafka app cannot transform using javascript engine

### ISSUE THREAD

**Issue by usopan** [spring-cloud-stream-app-starters/scriptable-transform#2]
Kafka app version : 
docker:springcloudstream/scriptable-transform-processor-kafka-09:1.2.0.RELEASE 

getting following exception.

```
Caused by: java.lang.IllegalArgumentException: javax.script.ScriptEngineManager is unable to create a script engine for language 'javascript'.
This may be due to a missing language implementation or an invalid language name.
 	at org.springframework.util.Assert.notNull(Assert.java:134) ~[spring-core-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.integration.scripting.jsr223.AbstractScriptExecutor.<init>(AbstractScriptExecutor.java:57) ~[spring-integration-scripting-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.integration.scripting.jsr223.DefaultScriptExecutor.<init>(DefaultScriptExecutor.java:39) ~[spring-integration-scripting-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.integration.scripting.jsr223.ScriptExecutorFactory.getScriptExecutor(ScriptExecutorFactory.java:34) ~[spring-integration-scripting-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.integration.dsl.scripting.DslScriptExecutingMessageProcessor.afterPropertiesSet(DslScriptExecutingMessageProcessor.java:109) ~[spring-integration-java-dsl-1.2.1.RELEASE.jar!/:na] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624) ~[spring-beans-4.3.7.RELEASE.jar!/:4.3.7.RELEASE] 
 	... 39 common frames omitted
```

**Comment by artembilan** [comment]
Looks like your JRE is missing `nashorn.jar` to load and execute Javascript.

**Comment by sabbyanandan** [comment]
Closing this since it is not related to the application. It's an environment specific issue.
